language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  app: solidarize-dev
  api_key:
    secure: wXWB6iDCC3TkdAhK/vi0Np6F0Dr1Dl7koGwOuU9VrEItQgoP5khnKBqc34A9TF0rg6B66M9SkSVPlxb3z7mRAZmva7afiYW9DYQf/+PD3K3TkJE9sb3ViYdJ+cjzaQL/tVh/rsAArQXlkHjCphk9c1WRtKQ43+pEKa0kJEoWdoLXeaM7cp39iTN3yGyizge2UFBJiRF4zCRqCq+ljIf8k3+djeVj7AixulkPq0xS/IlUQqswL/qhk83AlF0dE7srmCxl7JwnkxcaQHxcPFF6/JfMQFfYXBbXk67TrsFDeclINVXYZAl32NfUWs+q/MX/h3RhmU6waZDzTLCbpW2vxH5zYpagEne5npJMuzMlYkoRL/1UoJb7j9Dk0PV1XVfTxRdABa2drv3L/6SUhr5F25/X/FPie5OF80zXGhHQs4drkVRFKYcHuRYyeVEanRoAV+Zcn3LVw9KPUjSRrHSqeX39ZpDfypAGR9MSLEo6kO2qYOU4UiTabUWPeMCebbgeWR8o5JyJgn9H4WGJWyrLm8wDaNe3ZBnPxxUpXdzCz3G+qqxz5JWJt6PtTYNzgylev3ko6xvp3kqrk3JwRKXtpQ7jMWMXvWtB/TxsRabMWXXGmv7E8/9IKhstHPgCZQ7mYkS1hkmd0mJwTIdderAbnXW2djXq8/DySIQT1S8xFE4=
