language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  app: solidarize-dev
  api_key:
    secure: "ufuuTcGYPrPUgz/tWeXVId88zjHM2hpane0K3Le3w5ffF8Z9erQ3pLD2NEH9dpUp6NItTqxRcgwGoFeukLsIsts163vnaoQj9pp70F/spdQd5087G4oO1KRzHXN0dWMvk7I9L8oru2NTtizjT0G25PL/wn0GjiMbtyuLvF0ztyI6CzwrwYtDeB4uTGvQJOy/eZP+i9dVfB0FoKw4QrN6W/i+jMZxbVpBRDa1KUI+5qsDU8vd3yYlLu/OlCoP+wAAuRzd7uoUc62Q/VuW+vJ4BjvC8lT2032So9DTpd6VAIGNJHMrA7ihepalaHmknVuxjtQHZE6+vJZ/QBeN9sU4hQLCrZqrjR9bLhCy0HN+xXc7w3rJfS5EdVGNq059NybTYHZE/2vEwNESWXOQ/TkSQ7HHkIpUruAAUysHHKtn93HPG2SCYYH8S95yZb1XygBNocVQvHAiocQAKfQQBKnyoKPgRzjlbpHeiuACO2Wmrq9md/YyprgzP/w0BHEXERhCHal7XqdqlUnIgR88df0+roINnAKhVCCp3it51FlALI9fM07QXI7gvfjnKIKckRe0xrPmJcQHtZlBQsY/rv9A3cT6G5mCjIqhggcxEIiUaRvViqA93eA5Rys1DTGzoWf0qxxSNKiGgI1/A9zEtlLhUXScP1VPz5kyyKRSihkLh7s="
