language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  app: solidarize-dev
  api_key:
    secure: "BH1P/Rmtk4A9kD4bfcrmzpoaPFdEL2vGTyHHwgxS/DBDk8AhsPQw9lld+OuXZL7eP0F/kB26FHa6ZZ1XP7vLgdJqHUgk7hdv5/aSBRPXFN5P9ZVZQ+rPIXzAa811ExYfVNf9K5uqm24MukYmAr7krRwJDzYfAT6G4CTibIZcobTGHUN5tmJ9enLOwH4OA3+i+dl26Sw3e0ai9wZFpi5u64Sm1X7ebk/OUssXrVkZjPWgxmq3zkgXDdTQgdOVu5+9ccEPgoAiTzGXJVN+cpizE/pxEAdQrJ0Ca9N5jxVznQr8X7CS7LtJeTgKUqenEo4edtUXENXxtiAt/Vnas1xY1RXRqVm/IMwkGATeH8ZT5x5brbfCSCJ9ZeZSv/lDaWIVSmPYMj8Fy/vPORaUZgDmmnLrKMoEmWGeRUx4jR8LYrDVUsUlxIkxSIysKVlTjBfRNA+l+hcHSCdi6Fsi316hwcUSRg0d+GOc9e+zxjve/iQCA4wyrwGp8LgOHnM5egFOk0JATp8Pzid87sBHbdxXD70fsUy/QQ3q8zbUldP63zLkkzFDIEhtYobgycCKljIlNgRGvGZgyf5dbQoYOpiPmxJ4OKzmljbkQkrrFXska6Ef20AtSmCz+ve/yvbseeawjfvj3ZdePaINnOii9AvWXRriWrWbTYwmcxoE9KpKnFs="
