language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  app: solidarize-dev
  api_key:
    secure: "wnt/PjrnOsCAiwCalNr8FCuenX0sTg1j6Pi+Ct4VcRVZiU5aU+3YrQlphAe/ZzLRnp51qjB/EDliaoK2iF3zrTg61OFMgQ21OH6OuMxYYv01wDX3BsQE3Ck29jGFZBdLhknHNMec7Arw3ZvHdKP+8CKT6aXZA740z+xmP/CiAfeHYpXzjDtohW+ahAzXL9dolVlo0R4RmGVLIkvKeTfeSGofzujIF5eD17WjV6mocF1WBrCatRRqxhKwhe9DN/mLiucr/2N8/rn2Ew4J0ym0TsECAwAMzuvtdE9O8DAR5VHUDRm5tpx6JfKLLSXn6gmtaviXAY7KLZ2q7CAjd/ZsY5+dbe1icANLKWIgceK13X8I+ArMb/de60lL9kT80JxXX1nDlN+Uq/anLWunUXApueIEXOnODYV5cgveahDqMy4Y7ZqLq6mf4e4cM2cDNW3WxLYqs+YcBhq7zEm9YHsNjebLZwWcEbxhw+x85BHdZPBoaIeQ2oYWXKTTsRXZJbIHT0UiExcPMBxlXGjN3/WEtLY68dxLR8CpozI0n+WilkR721BuwUmuth2hVqpQE91pqSq166r7NYXOeoficC9vT+YL9y7dNIjeC/OuH3NGCNxNV3PeZEKZk9v+2Pek6AmD69DxwfoPoLTq0FNN5uSnjq941Sucx6Hqyfxg/0mNzhw="
